// src/components/sections/Projects.svelte
<script lang="ts">
    import { resolveIllustration } from "@/lib/project-illustrations";
    import { projects, type Project } from "@/lib/projects";

    const entries = projects;

    const demoLabel = (demoType: Project["demoType"]) =>
        demoType === "live" ? "Live preview" : "Video demo";
</script>

<section
    id="projects"
    aria-label="Projects"
    class="relative scroll-mt-28 px-4 py-20 sm:scroll-mt-32 sm:px-6 sm:py-24"
>
    <div class="mx-auto w-full max-w-360">
        <div class="mb-8 space-y-2 sm:mb-10 sm:space-y-3">
            <p
                class="m-0 text-xs font-medium tracking-[0.2em] text-(--muted-foreground) uppercase sm:text-sm sm:tracking-[0.22em]"
            >
                Portfolio
            </p>
            <h2
                class="m-0 text-4xl leading-tight font-medium tracking-tight text-(--foreground) sm:text-5xl md:text-6xl"
            >
                Projects
            </h2>
        </div>

        <div class="grid gap-4 sm:gap-5 lg:grid-cols-2">
            {#each entries as project (project.title)}
                {@render projectCard(project)}
            {/each}
        </div>
    </div>
</section>

{#snippet glassLayers()}
    <span
        class="pointer-events-none absolute inset-0 z-1 rounded-[inherit] backdrop-blur-md"
        aria-hidden="true"
    ></span>
    <span
        class="pointer-events-none absolute inset-0 z-2 rounded-[inherit] bg-white/20 dark:bg-black/20"
        aria-hidden="true"
    ></span>
    <span
        class="pointer-events-none absolute inset-0 z-3 rounded-[inherit] shadow-[inset_1px_1px_1px_rgba(255,255,255,0.6)] dark:shadow-[inset_1px_1px_1px_rgba(255,255,255,0.12)]"
        aria-hidden="true"
    ></span>
{/snippet}

{#snippet imagePlaceholder(title: string)}
    <div
        class="flex h-full w-full items-center justify-center bg-[color-mix(in_srgb,var(--foreground)_8%,transparent)]"
        aria-hidden="true"
    >
        <span
            class="text-4xl font-medium text-(--muted-foreground) sm:text-5xl"
        >
            {title.charAt(0)}
        </span>
    </div>
{/snippet}

{#snippet techPills(technologies: string[])}
    <ul class="m-0 flex list-none flex-wrap gap-2">
        {#each technologies as tech (tech)}
            <li>
                <span
                    class="inline-block rounded-full bg-[color-mix(in_srgb,var(--accent)_12%,transparent)] px-3 py-1 text-xs font-medium text-[color-mix(in_srgb,var(--foreground)_80%,transparent)] ring-1 ring-[color-mix(in_srgb,var(--accent)_20%,transparent)] sm:text-sm"
                >
                    {tech}
                </span>
            </li>
        {/each}
    </ul>
{/snippet}

{#snippet actionButton(
    href: string,
    label: string,
    ariaLabel: string,
    icon: "github" | "live" | "video",
)}
    <a
        {href}
        target="_blank"
        rel="noopener noreferrer"
        class="group/btn relative inline-flex w-full items-center justify-center gap-2 overflow-hidden rounded-full bg-transparent px-4 py-2.5 text-sm text-(--foreground) no-underline shadow-[0_8px_32px_rgba(0,0,0,0.22)] ring-1 ring-[color-mix(in_srgb,var(--foreground)_12%,transparent)] transition-[transform,box-shadow] duration-200 hover:scale-[1.03] hover:shadow-[0_12px_40px_rgba(0,0,0,0.3)] active:scale-[0.97] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-(--accent) motion-reduce:hover:scale-100 motion-reduce:active:scale-100 sm:w-auto sm:px-5 sm:text-base"
        aria-label={ariaLabel}
    >
        <span
            class="pointer-events-none absolute inset-0 z-1 rounded-[inherit] backdrop-blur-md"
            aria-hidden="true"
        ></span>
        <span
            class="pointer-events-none absolute inset-0 z-2 rounded-[inherit] bg-white/20 dark:bg-black/20"
            aria-hidden="true"
        ></span>
        <span
            class="pointer-events-none absolute inset-0 z-3 rounded-[inherit] bg-[color-mix(in_srgb,var(--accent)_0%,transparent)] transition-colors duration-200 group-hover/btn:bg-[color-mix(in_srgb,var(--accent)_10%,transparent)]"
            aria-hidden="true"
        ></span>

        {#if icon === "github"}
            <svg
                class="relative z-5 h-4 w-4 text-(--accent)"
                viewBox="0 0 24 24"
                fill="currentColor"
                aria-hidden="true"
            >
                <path
                    d="M12 0C5.374 0 0 5.373 0 12c0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"
                />
            </svg>
        {:else if icon === "live"}
            <svg
                class="relative z-5 h-4 w-4 text-(--accent)"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                aria-hidden="true"
            >
                <path d="M7 17 17 7" />
                <path d="M9 7h8v8" />
            </svg>
        {:else}
            <svg
                class="relative z-5 h-4 w-4 text-(--accent)"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                aria-hidden="true"
            >
                <polygon points="5 3 19 12 5 21 5 3" />
            </svg>
        {/if}

        <span class="relative z-5 font-medium">{label}</span>
    </a>
{/snippet}

{#snippet projectCard(project: Project)}
    {@const Illustration = resolveIllustration(project.image)}
    <article
        class="group/card relative flex h-full flex-col overflow-hidden rounded-2xl bg-transparent shadow-[0_8px_32px_rgba(0,0,0,0.22)] ring-1 ring-[color-mix(in_srgb,var(--foreground)_12%,transparent)] transition-[box-shadow] duration-200 hover:shadow-[0_12px_40px_rgba(0,0,0,0.3)]"
    >
        {@render glassLayers()}

        <div class="relative z-4 flex min-h-0 flex-1 flex-col">
            <div class="relative aspect-video shrink-0 overflow-hidden rounded-t-2xl">
                {#if Illustration}
                    <Illustration
                        class="h-full w-full transition-transform duration-300 group-hover/card:scale-[1.02] motion-reduce:group-hover/card:scale-100"
                    />
                {:else}
                    {@render imagePlaceholder(project.title)}
                {/if}
            </div>

            <div class="flex flex-1 flex-col gap-4 p-4 sm:gap-5 sm:p-6">
                <div class="space-y-2.5">
                    <h3 class="m-0 text-xl leading-tight font-medium text-(--foreground) sm:text-2xl">
                        {project.title}
                    </h3>
                    <p
                        class="m-0 text-sm leading-relaxed text-[color-mix(in_srgb,var(--foreground)_72%,transparent)] max-sm:line-clamp-4 sm:text-base"
                    >
                        {project.description}
                    </p>
                </div>

                {@render techPills(project.technologies)}

                <div class="mt-auto flex flex-col gap-3 pt-2 sm:flex-row sm:items-center sm:justify-between">
                    {@render actionButton(
                        project.demo,
                        demoLabel(project.demoType),
                        `${demoLabel(project.demoType)} for ${project.title}`,
                        project.demoType === "live" ? "live" : "video",
                    )}
                    {@render actionButton(
                        project.github,
                        "Source",
                        `View source code for ${project.title}`,
                        "github",
                    )}
                </div>
            </div>
        </div>
    </article>
{/snippet}

// src/components/Projects.tsx
import React from 'react';
import projectsData from '../data/projects.json';
import { kineGit, portfolioWebsite, ocbcVTM, facialRecognition } from '../assets';

interface Project {
  title: string;
  description: string;
  technologies: string[];
  github: string;
  demo: string;
  image: string;
}

interface ProjectCardProps {
  project: Project;
  index: number;
}

const getProjectImage = (imagePath: string): string | null => {
  switch (imagePath) {
    case '/assets/projectsImg/portfolioWebsite.png':
      return portfolioWebsite.src;
    case '/assets/projectsImg/kineGit.png':
      return kineGit.src;
    case '/assets/projectsImg/ocbcVTM.png':
      return ocbcVTM.src;
    case '/assets/projectsImg/facialRecognition.png':
      return facialRecognition.src;
    case '/placeholder-project.jpg':
      return null;
    default:
      return null;
  }
};

const ProjectCard: React.FC<ProjectCardProps> = ({ project, index }) => {
  return (
    <div
      className="group relative bg-white dark:bg-gray-800 rounded-3xl shadow-lg hover:shadow-2xl transition-all duration-500 hover:scale-[1.02] border border-gray-100 dark:border-gray-700 overflow-hidden"
      style={{ animationDelay: `${index * 150}ms` }}
    >
      <div className="absolute inset-0 bg-gradient-to-br from-blue-50 via-white to-purple-50 dark:from-gray-900 dark:via-gray-800 dark:to-purple-900/20 rounded-3xl"></div>

      <div className="absolute inset-0 bg-gradient-to-br from-blue-200 via-purple-200 to-pink-200 dark:from-blue-500/20 dark:via-purple-500/20 dark:to-pink-500/20 rounded-3xl p-[1px]">
        <div className="w-full h-full bg-white/80 dark:bg-gray-900/80 backdrop-blur-sm rounded-3xl"></div>
      </div>

      <div className="relative p-8 h-full flex flex-col">
        <div className="w-full h-48 bg-gradient-to-br from-blue-100 to-purple-100 dark:from-gray-700 dark:to-purple-900/30 rounded-2xl mb-6 overflow-hidden">
          {(() => {
            const imageSrc = getProjectImage(project.image);
            return imageSrc ? (
              <img
                src={imageSrc}
                alt={`${project.title} preview`}
                className="w-full h-full object-cover rounded-2xl"
                onError={(e) => {
                  const target = e.target as HTMLImageElement;
                  target.style.display = 'none';
                  if (target.parentElement) {
                    target.parentElement.innerHTML = `
                      <div class="w-full h-full flex items-center justify-center">
                        <div class="text-6xl opacity-20">🚀</div>
                      </div>
                    `;
                  }
                }}
              />
            ) : (
              <div className="w-full h-full flex items-center justify-center">
                <div className="text-6xl opacity-20">🚀</div>
              </div>
            );
          })()}
        </div>

        <h3 className="text-xl font-bold text-gray-900 dark:text-white mb-4 leading-tight">
          {project.title}
        </h3>

        <p className="text-gray-600 dark:text-gray-300 mb-6 flex-grow leading-relaxed">
          {project.description}
        </p>

        <div className="mb-6">
          <div className="flex flex-wrap gap-2">
            {project.technologies.map((tech, techIndex) => (
              <span
                key={techIndex}
                className="inline-flex items-center px-3 py-1 bg-gradient-to-r from-blue-500/10 to-purple-500/10 dark:from-blue-400/20 dark:to-purple-400/20 text-blue-700 dark:text-blue-300 text-sm font-medium rounded-full border border-blue-200 dark:border-blue-700"
              >
                {tech}
              </span>
            ))}
          </div>
        </div>

        <div className="flex flex-col sm:flex-row gap-3 sm:gap-4 mt-auto">
          <a
            href={project.github}
            target="_blank"
            rel="noopener noreferrer"
            className="flex-1 group/btn relative inline-flex items-center justify-center px-4 sm:px-6 py-3 bg-gradient-to-r from-gray-700 to-gray-900 dark:from-gray-600 dark:to-gray-800 text-white font-semibold rounded-2xl shadow-lg hover:shadow-xl transform hover:scale-[1.02] transition-all duration-300 overflow-hidden"
          >
            <div className="absolute inset-0 bg-gradient-to-r from-gray-600 to-gray-800 opacity-0 group-hover/btn:opacity-100 transition-opacity duration-300"></div>
            <svg className="w-4 h-4 mr-2 relative z-10" fill="currentColor" viewBox="0 0 20 20">
              <path fillRule="evenodd" d="M10 0C4.477 0 0 4.484 0 10.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0110 4.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.203 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.942.359.31.678.921.678 1.856 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0020 10.017C20 4.484 15.522 0 10 0z" clipRule="evenodd" />
            </svg>
            <span className="relative z-10 text-sm">GitHub</span>
          </a>

          <a
            href={project.demo}
            target="_blank"
            rel="noopener noreferrer"
            className="flex-1 group/btn relative inline-flex items-center justify-center px-4 sm:px-6 py-3 bg-gradient-to-r from-blue-600 via-purple-600 to-blue-700 text-white font-semibold rounded-2xl shadow-lg hover:shadow-xl transform hover:scale-[1.02] transition-all duration-300 overflow-hidden"
          >
            <div className="absolute inset-0 bg-gradient-to-r from-blue-600 via-purple-600 to-pink-600 opacity-0 group-hover/btn:opacity-100 transition-opacity duration-300"></div>
            <svg className="w-4 h-4 mr-2 relative z-10" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
            </svg>
            <span className="relative z-10 text-sm">{project.title === 'OCBC Virtual Teller Machine' || project.title === 'Facial Recognition Authentication' ? 'Video Demo' : 'Live Demo'}</span>
          </a>
        </div>
      </div>
    </div>
  );
};

export const Projects: React.FC = () => {
  return (
    <section id="projects" className="py-16 sm:py-24 px-4 sm:px-6 relative">
      <div className="max-w-7xl mx-auto relative">
        <div className="text-center mb-20">
          <h2 className="text-5xl md:text-6xl lg:text-7xl font-bold bg-gradient-to-r from-gray-900 via-blue-900 to-purple-900 dark:from-white dark:via-blue-100 dark:to-purple-100 bg-clip-text text-transparent mb-6">
            Projects
          </h2>
          <p className="text-xl text-gray-600 dark:text-gray-300 max-w-3xl mx-auto">
            A collection of projects that showcase my development skills and passion for creating innovative solutions
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {projectsData.map((project, index) => (
            <ProjectCard
              key={project.title}
              project={project}
              index={index}
            />
          ))}
        </div>
      </div>
    </section>
  );
};
